### PR TITLE
Update base.config

### PR DESCRIPTION
**Pull request by ajfriedman18**
updated to better align with omics cpu-mem ratios

*Description of changes:*
updated cpu and memory of `base.config` to help deal with certain tools that have cpu spike bugs (eg dupradar)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by markjschreiber — APPROVED** [review]
LGTM

**Review by wleepang — COMMENTED** [review]
We should put these Omics specific resource configurations in `./conf/omics.config`. That way the `base.config` can stay the same as upstream, where they were developed for local and HPC execution. The omics.config is included in the nextflow.config such that it will override base.config where appropriate.

We should also make this change to all other nf-core based example workflows.

**Review by wleepang — CHANGES_REQUESTED** [review]
see prior comment for requested changes

**Comment by ajfriedman18** [comment]
@wleepang believe I moved that correctly now. sorry for delay

**Review by wleepang — APPROVED** [review]

**Pull request merged**
